sudo: false
language: node_js
node_js:
  - '8'
  - 'lts/*'
matrix:
  fast_finish: true
script: npm run prepare
after_success: npm run coveralls
notifications:
  email:
    recipients:
      - albertgaohy@gmail.com
    on_success: never # default: change
    on_failure: always # default: always